# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/customizing-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/change-codemod
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - change/squad-fe-framework
    labels:
      - dependencies
      - fe-framework
  - package-ecosystem: npm
    directory: /eslint-config-change-base
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - change/packages/squad-fe-framework
    labels:
      - dependencies
      - fe-framework
  - package-ecosystem: npm
    directory: /packages/eslint-config-change-fe
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - change/squad-fe-framework
    labels:
      - dependencies
      - fe-framework
  - package-ecosystem: npm
    directory: /packages/eslint-plugin-change
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - change/squad-fe-framework
    labels:
      - dependencies
      - fe-framework
